
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto
package example

const (
	Simple_HelloWorld = "/example.Simple/HelloWorld"
)

var (
	FullMethods = []string{
		Simple_HelloWorld,
	}
)

