// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloWorldMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldMessage) Reset()         { *m = HelloWorldMessage{} }
func (m *HelloWorldMessage) String() string { return proto.CompactTextString(m) }
func (*HelloWorldMessage) ProtoMessage()    {}
func (*HelloWorldMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_92482bb7efaf4b1a, []int{0}
}
func (m *HelloWorldMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldMessage.Unmarshal(m, b)
}
func (m *HelloWorldMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldMessage.Marshal(b, m, deterministic)
}
func (dst *HelloWorldMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldMessage.Merge(dst, src)
}
func (m *HelloWorldMessage) XXX_Size() int {
	return xxx_messageInfo_HelloWorldMessage.Size(m)
}
func (m *HelloWorldMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldMessage proto.InternalMessageInfo

func (m *HelloWorldMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloWorldMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

var E_Foo = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50001,
	Name:          "example.foo",
	Tag:           "bytes,50001,opt,name=foo",
	Filename:      "example.proto",
}

func init() {
	proto.RegisterType((*HelloWorldMessage)(nil), "example.HelloWorldMessage")
	proto.RegisterExtension(E_Foo)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SimpleClient is the client API for Simple service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimpleClient interface {
	HelloWorld(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HelloWorldMessage, error)
}

type simpleClient struct {
	cc *grpc.ClientConn
}

func NewSimpleClient(cc *grpc.ClientConn) SimpleClient {
	return &simpleClient{cc}
}

func (c *simpleClient) HelloWorld(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HelloWorldMessage, error) {
	out := new(HelloWorldMessage)
	err := c.cc.Invoke(ctx, "/example.Simple/HelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleServer is the server API for Simple service.
type SimpleServer interface {
	HelloWorld(context.Context, *empty.Empty) (*HelloWorldMessage, error)
}

func RegisterSimpleServer(s *grpc.Server, srv SimpleServer) {
	s.RegisterService(&_Simple_serviceDesc, srv)
}

func _Simple_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Simple/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleServer).HelloWorld(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Simple_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.Simple",
	HandlerType: (*SimpleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _Simple_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_example_92482bb7efaf4b1a) }

var fileDescriptor_example_92482bb7efaf4b1a = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0xa5, 0xa4, 0xd3,
	0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0xc2, 0x49, 0xa5, 0x69, 0xfa, 0xa9, 0xb9, 0x05, 0x25,
	0x95, 0x10, 0x55, 0x52, 0x32, 0x50, 0xc9, 0xc4, 0x82, 0x4c, 0xfd, 0xc4, 0xbc, 0xbc, 0xfc, 0x92,
	0xc4, 0x92, 0xcc, 0xfc, 0xbc, 0x62, 0xa8, 0xac, 0x02, 0xba, 0xd6, 0x94, 0xd4, 0xe2, 0xe4, 0xa2,
	0xcc, 0x82, 0x92, 0xfc, 0x22, 0x88, 0x0a, 0x25, 0x2f, 0x2e, 0x41, 0x8f, 0xd4, 0x9c, 0x9c, 0xfc,
	0xf0, 0xfc, 0xa2, 0x9c, 0x14, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x21, 0x21, 0x2e, 0x96,
	0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x82, 0x8b,
	0x3d, 0x17, 0x22, 0x2d, 0xc1, 0x04, 0x16, 0x86, 0x71, 0xad, 0xd8, 0xbb, 0xb6, 0x4a, 0x30, 0x27,
	0x25, 0x16, 0x19, 0xa5, 0x70, 0xb1, 0x05, 0x67, 0x82, 0x9c, 0x2c, 0x14, 0xc5, 0xc5, 0x85, 0x30,
	0x55, 0x48, 0x4c, 0x0f, 0xe2, 0x0c, 0x3d, 0x98, 0x33, 0xf4, 0x5c, 0x41, 0x3e, 0x90, 0x92, 0xd2,
	0x83, 0xf9, 0x18, 0xc3, 0x09, 0x4a, 0x12, 0x4d, 0x97, 0x9f, 0x4c, 0x66, 0x12, 0x12, 0x12, 0xd0,
	0x2f, 0x33, 0xd4, 0x87, 0x2a, 0xd3, 0x4f, 0x4d, 0xce, 0xc8, 0xb7, 0x32, 0xe6, 0x62, 0x4e, 0xcb,
	0xcf, 0x17, 0x92, 0xc7, 0x30, 0x14, 0xaa, 0xd5, 0xbf, 0x00, 0x1c, 0x02, 0x12, 0x17, 0xdb, 0x98,
	0xc1, 0xee, 0x04, 0xa9, 0x76, 0xe2, 0x8c, 0x82, 0x05, 0x67, 0x12, 0x1b, 0x58, 0x83, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0xf1, 0xee, 0x5a, 0xeb, 0x6f, 0x01, 0x00, 0x00,
}
