package template

import lib "github.com/zokypesch/protoc-gen-generator/lib"

var tmplFullMethod = `
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: {{ .FileName }}
package {{ .GoPackage }}

const (
{{- range $service := .Services }}
{{- range $method := $service.Methods }}
	{{ $service.Name }}_{{ $method.Name }} = "/{{ $.Package }}.{{ $service.Name }}/{{ $method.Name }}"
{{- end}}
{{- end}}
)

var (
	FullMethods = []string{{ "{" }}
{{- range $service := .Services }}
{{- range $method := $service.Methods }}
		{{ $service.Name }}_{{ $method.Name }},
{{- end}}
{{- end}}
	{{ "}" }}
)
`

var ListFullMethod = lib.List{
	FileType: ".custom.pb.go",
	Template: tmplFullMethod,
	Location: "",
	Lang:     "go",
}
