package template

import lib "github.com/zokypesch/protoc-gen-generator/lib"

var tmplHandler = `package handler

// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: {{ .FileName }}_{{ .GoPackage }}
// File Location: handler/{{ ucfirst (getFirstService .Services).Name }}.handler.go

import  (
	pb "{{ .Src }}/grpc/pb/{{ .GoPackage }}"
	"context"
	{{- if .UseEmptyProto}}
	empty "github.com/golang/protobuf/ptypes/empty"
	{{- end}}
	validator "github.com/go-playground/validator"
	domain "{{ .Src }}/{{ ucdown (getFirstService .Services).Name }}"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

{{- range $service := .Services }}
type {{ ucfirst $service.Name }} struct{
	svc *domain.{{ ucfirst $service.Name }}Service
	validate *validator.Validate
}

func New{{ ucfirst $service.Name }}(svc *domain.{{ ucfirst $service.Name }}Service) *{{ ucfirst $service.Name }} {
	validate := validator.New()
	return &{{ ucfirst $service.Name }}{{ unescape "{" }}svc, validate{{ unescape "}" }}
}

{{- range $method := $service.Methods }}
// {{ ucfirst $method.Name }} method declare by generated code
{{- if eq $method.Input "empty"}}
func (handler *{{ ucfirst $service.Name }}) {{ ucfirst $method.Name }}(ctx context.Context, in *empty.Empty) (*pb.{{ ucfirst $method.Output }}, error) {
{{- else}}
func (handler *{{ ucfirst $service.Name }}) {{ ucfirst $method.Name }}(ctx context.Context, in *pb.{{ ucfirst $method.Input }}) (*pb.{{ ucfirst $method.Output }}, error) {
{{- end}}

{{- if eq $method.Input "empty"}}
{{- else}}
	model := domain.{{ ucfirst $method.Input }}{}

{{- range $field := $method.InputWithAgregator.Fields }}
{{- if $field.RequiredOption}}
{{- if eq $field.TypeDataGo "time.Time"}}
{{- else }}
	model.{{ ucfirst $field.Name }} = in.{{ ucfirst $field.Name }}
{{- end}}
{{- end}}
{{- end}}

	if err := handler.validate.Struct(model); err != nil {
		return &pb.{{ ucfirst $method.Output }}{}, status.Errorf(codes.InvalidArgument, err.Error())
	}
{{- end}}
	return handler.svc.{{ ucfirst $method.Name }}(ctx, in)
}
{{- end}}
{{- end}}

`

var ListHandler = lib.List{
	FileType: ".handler.go",
	Template: tmplHandler,
	Location: "./handler/",
	Lang:     "go",
}
