package template

import lib "github.com/zokypesch/protoc-gen-generator/lib"

var tmplModelGo = `package model

// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: {{ .FileName }}_{{ .GoPackage }}
// File Location: model/{{ ucfirst (getFirstService .Services).Name }}.model.go

{{- range $msg := .Messages }}
// {{ ucfirst $msg.Name }} for struct info
type {{ ucfirst $msg.Name }} struct {
{{- range $field := $msg.Fields }}
	{{ $field.NameGo }}			{{ $field.TypeDataGo }} {{- if eq $field.Tag "" }} {{- else}} '{{ unescape $field.Tag }}' {{- end}}
{{- end}}
}
{{- end}}

{{- range $enum := .Enums }}
type {{ ucfirst $enum.Name }} int32

{{- end}}

{{- if .Elastic }}
{{- range $msg := .Messages }}

{{- if $msg.IsElastic }}

const Mapping{{ ucfirst $msg.Name }} = '{
	"settings":{
		"number_of_shards": 1,
		"number_of_replicas": 0
	},
	"mappings":{
		"inbox":{
			"properties":{
			{{- range $field := $msg.Fields }}
				{{- if $field.FullText}}
				"{{ ucdown $field.Name }}":{
					"type":"text",
					"store": true,
					"fielddata": true
				}{{- if eq $msg.NumField $field.Index}} {{- else}}, {{- end}}
				{{- else}}
				"{{ ucdown $field.Name }}":{
					"type":"keyword"
				}{{- if eq $msg.NumField $field.Index}} {{- else}}, {{- end}}
				{{- end}}
			{{- end}}
			}
		}
	}
}'

{{- end}}

{{- end}}
{{- end}}

`

var ListModelGolang = lib.List{
	FileType:     ".model.go",
	Template:     tmplModelGo,
	Location:     "./model/",
	Lang:         "go",
	ReplaceQuote: true,
}
