package template

import lib "github.com/zokypesch/protoc-gen-generator/lib"

var tmplModelGo = `package model

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: {{ .FileName }}_{{ .GoPackage }}
// File Location: model/{{ ucfirst (getFirstService .Services).Name }}.model.go

{{- range $msg := .Messages }}
// {{ ucfirst $msg.Name }} for struct info
type {{ ucfirst $msg.Name }} struct {
{{- range $field := $msg.Fields }}
	{{ $field.NameGo }}			{{ $field.TypeDataGo }} {{- if $field.IgnoreGorm}} 'gorm:"-"' {{- end}}
{{- end}}
}
{{- end}}

{{- range $enum := .Enums }}
type {{ ucfirst $enum.Name }} int32

{{- end}}

`

var ListModelGolang = lib.List{
	FileType:     ".model.go",
	Template:     tmplModelGo,
	Location:     "./model/",
	Lang:         "go",
	ReplaceQuote: true,
}
