package template

import lib "github.com/zokypesch/protoc-gen-generator/lib"

var tmplRepositoryGo = `package repo

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: {{ .FileName }}_{{ .GoPackage }}
// File Location: repo/{{ ucfirst (getFirstService .Services).Name }}.repository.go

import (
	"github.com/jinzhu/gorm"
	model "{{ .Src }}/model"
)

{{- range $msg := .Messages }}
{{- if $msg.IsRepository}} 

// {{ ucfirst $msg.Name }} for struct info
type {{ ucfirst $msg.Name }}Repository struct {
	db *gorm.DB
}

// {{ ucfirst $msg.Name }}Service for interfacing repository
type {{ ucfirst $msg.Name }}Service interface {
	GetBy{{ $msg.PrimaryKeyName }}(payload *model.{{ ucfirst $msg.Name }}) (*model.{{ucfirst $msg.Name}}, error)
	GetAll(payload *model.{{ ucfirst $msg.Name }}) ([]model.{{ ucfirst $msg.Name }}, error)
	Create(payload *model.{{ ucfirst $msg.Name }}) (*model.{{ucfirst $msg.Name}}, error)
	Update(payload *model.{{ ucfirst $msg.Name }}) (*model.{{ ucfirst $msg.Name }}, error)
	Delete(payload *model.{{ ucfirst $msg.Name }}) (*model.{{ ucfirst $msg.Name }}, error)
}

// {{ ucfirst $msg.Name }} for repository singleton
var {{ $msg.Name }}Repo {{ ucfirst $msg.Name }}Service

// New{{ ucfirst $msg.Name }}Service for new repository service
func New{{ ucfirst $msg.Name }}Service(db *gorm.DB) {{ ucfirst $msg.Name }}Service {
	if {{ $msg.Name }}Repo == nil {
		{{ $msg.Name }}Repo = &{{ ucfirst $msg.Name }}Repository{
			db,
		}
	}
	return {{ $msg.Name }}Repo
}

// GetBy{{ $msg.PrimaryKeyName }} for get by primarykey
func (repo *{{ ucfirst $msg.Name }}Repository) GetBy{{ $msg.PrimaryKeyName }}(payload *model.{{ ucfirst $msg.Name }}) (*model.{{ ucfirst $msg.Name }}, error) {
	var data model.{{ ucfirst $msg.Name }}
	db := repo.db.Where("{{ underscore $msg.PrimaryKeyName }} = ?", payload.{{ ucfirst $msg.PrimaryKeyName }}).Find(&data)

	return &data, db.Error
}

// GetAll for get all from table
func (repo *{{ ucfirst $msg.Name }}Repository) GetAll(payload *model.{{ ucfirst $msg.Name }}) ([]model.{{ ucfirst $msg.Name }}, error) {
	limit := 1000
	page := 1
	offset := (int(page) - 1) * limit

	var data []model.{{ ucfirst $msg.Name }} 
	db := repo.db.Where(payload).Offset(offset).Limit(limit).Find(&data)

	return data, db.Error

}

// Create for create database
func (repo *{{ ucfirst $msg.Name }}Repository) Create(payload *model.{{ ucfirst $msg.Name }}) (*model.{{ ucfirst $msg.Name }}, error) {
	err := repo.db.Create(payload).Error

	return payload, err
}

// Update for update data
func (repo *{{ ucfirst $msg.Name }}Repository) Update(payload *model.{{ ucfirst $msg.Name }}) (*model.{{ ucfirst $msg.Name }}, error) {
	err := repo.db.Model(&model.{{ ucfirst $msg.Name }}{{unescape "{"}}{{ $msg.PrimaryKeyName }}: payload.{{ ucfirst $msg.PrimaryKeyName }}{{unescape "}"}}).Update(payload).Error

	return payload, err
}

// Delete for delete data
func (repo *{{ ucfirst $msg.Name }}Repository) Delete(payload *model.{{ ucfirst $msg.Name }}) (*model.{{ ucfirst $msg.Name }}, error) {
	err := repo.db.Delete(model.{{ ucfirst $msg.Name }}{{unescape "{"}}{{unescape "}"}}, "{{ underscore $msg.PrimaryKeyName }} = ?", payload.{{ ucfirst $msg.PrimaryKeyName }}).Error

	return payload, err
}

{{- end}}

{{- end}}



`

var ListRepositoryGolang = lib.List{
	FileType: ".repository.go",
	Template: tmplRepositoryGo,
	Location: "./repo/",
	Lang:     "go",
}
