package template

import lib "github.com/zokypesch/protoc-gen-generator/lib"

var tmplService = `package handler

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: {{ .FileName }}_{{ .GoPackage }}
// File Location: handler/{{ ucfirst (getFirstService .Services).Name }}.service.go

import  (
	pb "{{ .Src }}/grpc/pb/{{ .GoPackage }}"
	"context"
	// "fmt"
	empty "github.com/golang/protobuf/ptypes/empty"
	repo "{{ .Src }}/repo"
	{{- if .Elastic }}
	core "{{ .Src }}/core"
	{{- end}}
	model "{{ .Src }}/model"
)

{{- range $service := .Services }}
type {{ ucfirst $service.Name }}Service struct{
	repo *repo.MasterRepository
	{{if $service.Elastic }}
	{{- range $msg := $service.AllMessage }}
	{{- if $msg.IsElastic }}
	es{{ ucfirst $msg.Name }} core.ESModule
	{{- end}}
	{{- end}}
	{{- end}}
}

// {{ ucfirst $service.Name }}Svc for service singleton
var {{ $service.Name }}Svc *{{ ucfirst $service.Name }}Service

// New{{ ucfirst $service.Name }}Service for new repository service
{{if $service.Elastic }}
func New{{ ucfirst $service.Name }}Service(repo *repo.MasterRepository,{{ $service.MessageAllEs }}) *{{ ucfirst $service.Name }}Service {
{{- else}}
func New{{ ucfirst $service.Name }}Service(repo *repo.MasterRepository) *{{ ucfirst $service.Name }}Service {
{{- end}}
	if {{ $service.Name }}Svc == nil {
		{{ $service.Name }}Svc = &{{ ucfirst $service.Name }}Service{
			repo,
			{{- range $msg := $service.AllMessage }}
			{{- if $msg.IsElastic }}
			es{{ ucfirst $msg.Name }},
			{{- end}}
			{{- end}}
		}
	}
	return {{ $service.Name }}Svc
}

{{- range $method := $service.Methods }}
// {{ ucfirst $method.Name }} method declare by generated code
{{- if eq $method.Input "empty"}}
func (svc *{{ ucfirst $service.Name }}Service) {{ ucfirst $method.Name }}(ctx context.Context, in *empty.Empty) (*pb.{{ ucfirst $method.Output }}, error) {
{{- else}}
func (svc *{{ ucfirst $service.Name }}Service) {{ ucfirst $method.Name }}(ctx context.Context, in *pb.{{ ucfirst $method.Input }}) (*pb.{{ ucfirst $method.Output }}, error) {
{{- end}}

{{- if eq $method.Input "empty"}}
	return &pb.{{ ucfirst $method.Output }}{}, nil
{{- else}}
{{- if $method.IsAgregator}}
	model := &model.{{ ucfirst $method.AgregatorMessage.Name }}{}
{{- range $field := $method.InputWithAgregator.Fields }}
{{- if eq $field.IgnoreGorm false}}
	model.{{ ucfirst $field.Name }} = in.{{ ucfirst $field.Name }}
{{- end}}
{{- end}}
	_, err := svc.repo.{{ ucfirst $method.AgregatorMessage.Name }}.{{ $method.AgregatorFunction }}(model)

	resp := &pb.{{ ucfirst $method.Output }}{}
{{- range $field := $method.IO.Fields }}
{{- if eq $field.IgnoreGorm false }}
	resp.{{ ucfirst $field.Name }} = model.{{ ucfirst $field.Name }}
{{- end}}
{{- end}}
	return resp, err

{{- else}}
	return &pb.{{ ucfirst $method.Output }}{}, nil
{{- end}}
{{- end}}
}
{{- end}}
{{- end}}

`

var ListService = lib.List{
	FileType: ".service.go",
	Template: tmplService,
	Location: "./handler/",
	Lang:     "go",
}
