package template

import lib "github.com/zokypesch/protoc-gen-generator/lib"

var tmplTypeScriptVal = `
// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: {{ .FileName }}_{{ .GoPackage }}
// File Location: validation/{{ ucfirst (getFirstService .Services).Name }}.ts

import {MinLength, MaxLength, IsEmail, IsNumberString} from "class-validator";

{{- range $msg := .Messages }}
export default class {{ ucfirst $msg.Name }} {
{{- range $field := $msg.Fields }}
{{- if $field.RequiredOption}}
	@MinLength(5, {
		message: '{{ $field.ErrorDesc }}'
	})
	{{ ucdown $field.Name }}: {{ $field.TypeData }};
{{- end}}
{{- end}}
	constructor({{- range $field := $msg.Fields }}{{- if $field.RequiredOption}} {{ ucdown $field.Name }}: {{ $field.TypeData }} {{- if eq $msg.NumField $field.Index }}{{- else}}, {{- end}}{{- end}}{{- end}}) {
		{{- range $field := $msg.Fields }}
		{{- if $field.RequiredOption}}
		this.{{ ucdown $field.Name }} = {{ ucdown $field.Name }};
		{{- end}}
		{{- end}}
	}
}
{{- end}}

`
var ListTypeScriptValidation = lib.List{
	FileType: ".validation.ts",
	Template: tmplTypeScriptVal,
	Location: "./typescript/",
	Lang:     "ts",
}
