package model

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto_example
// File Location: model/Simple.model.go
// HelloWorldMessage for struct info
type HelloWorldMessage struct {
	Name			string
	Message			string
}


