
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto_example
// File Location: api/Simple.ts

import {defaultProps, Api} from "./ApiConfig"
import {buildParams} from "./Util"
export interface helloWorldMessage {
	name:string
	message:string
}

interface OutputGeneral<T> {
    loading: boolean,
    data?: T,
    error: string | null | undefined
    isRefreshing: boolean
}
export type OutputHelloWorld = OutputGeneral<helloWorldMessage>
class Simple {
	props: defaultProps;
    constructor(params: defaultProps) {
        this.props = params
	}
	HelloWorld = () => Api(this.props).get("/v1/example/echo")
}
export default Simple


