package repo

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto_example
// File Location: repo/Simple.repository.go

import (
	"github.com/jinzhu/gorm"
	model "github.com/zokypesch/protoc-gen-generator/model"
)




