package repo

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto_example
// File Location: repo/Simple.master.repository.go

import (
	"github.com/jinzhu/gorm"
)

// MasterRepository for factory repository
type MasterRepository struct {
}
var masterRepo *MasterRepository

// NewMasterRepoService for new repository event service
func NewMasterRepoService(db *gorm.DB) *MasterRepository {
	if masterRepo == nil {
		masterRepo = &MasterRepository{
		}
	}
	return masterRepo
}

